// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackgroundAnimate: typeof import('./components/BackgroundAnimate.vue')['default']
    DynamicText: typeof import('./components/DynamicText.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextChanger: typeof import('./components/TextChanger.vue')['default']
  }
}
