// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateCircleBg: typeof import('./components/reuseables/animateCircleBg.vue')['default']
    'BaseModa;': typeof import('./components/reuseables/base-moda
    BaseModal: typeof import('./components/reuseables/baseModal.vue')['default']
    CloseCircle: typeof import('./components/closeCircle.vue')['default']
    Loader: typeof import('./components/reuseables/loader.vue')['default']
    ProgressBar: typeof import('./components/progressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
